#!/bin/bash
current_state=$(defaults read com.apple.dock window-tiling-enabled)
if [ "$current_state" = "1" ]; then
    defaults write com.apple.dock window-tiling-enabled -bool false
    defaults write com.apple.dock window-tiling-margin -int 0
else
    defaults write com.apple.dock window-tiling-enabled -bool true
    defaults write com.apple.dock window-tiling-margin -int 5
fi
killall Dock